/**
 * autolink-js - https://github.com/bryanwoods/autolink-js
 **/
// Generated by CoffeeScript 1.10.0
(function() {
  var autoLink,
	slice = [].slice;

  autoLink = function() {
	var callback, k, linkAttributes, option, options, pattern, v;
	options = 1 <= arguments.length ? slice.call(arguments, 0) : [];
	pattern = /(^|[\s\n]|<[A-Za-z]*\/?>)((?:https?|ftp):\/\/[\-A-Z0-9+\u0026\u2019@#\/%?=()~_|!:,.;]*[\-A-Z0-9+\u0026@#\/%=~()_|])/gi;
	if (!(options.length > 0)) {
	  return this.replace(pattern, "$1<a href='$2'>$2</a>");
	}
	option = options[0];
	callback = option["callback"];
	linkAttributes = ((function() {
	  var results;
	  results = [];
	  for (k in option) {
		v = option[k];
		if (k !== 'callback') {
		  results.push(" " + k + "='" + v + "'");
		}
	  }
	  return results;
	})()).join('');
	return this.replace(pattern, function(match, space, url) {
	  var link;
	  link = (typeof callback === "function" ? callback(url) : void 0) || ("<a href='" + url + "'" + linkAttributes + ">" + url + "</a>");
	  return "" + space + link;
	});
  };

  String.prototype['autoLink'] = autoLink;

}).call(this);
/**
 * end of autolink-js
 **/

// current script version
var __VERSION = "1.0.0";
// end version

jQuery(document).ready(function () {
	
	var _FontSize = 12;
	var _TextareaX = 300;
	var _TextareaY = 50;
	var _BackgroundColor = "#121";
	var _NewMessagesStar = 0;
	var _HideStuffInKarma_ILLEGAL_JUMP = 0;
	var _HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING = 0;
	var _HideStuffInKarma_WALL_HACK = 0;
	var _HideStuffInKarma_TANK_ACCELERATION = 0;
	var _HideStuffInKarma_Flood = 0;
	var _HideStuffInKarma_VERTICAL_MOVEMENT = 0;
	
	var _CommentsMenu = 1;
	var _Comments = "";
	var _BanReasons = "";
	var _language = "";
	
	jQuery.fn.LoadSettings = function () {
		try { _FontSize = localStorage['FontSize']; } catch (e) { _FontSize = 14; }
		try { _TextareaX = localStorage['TextareaX']; } catch (e) { _TextareaX = 300; }
		try { _TextareaY = localStorage['TextareaY']; } catch (e) { _TextareaY = 50; }
		try { _BackgroundColor = localStorage['BackgroundColor']; } catch (e) { _BackgroundColor = "#121"; }
		try { _NewMessagesStar = parseInt(localStorage['NewMessagesStar']); } catch (e) { _NewMessagesStar = 0; }
		try { _HideStuffInKarma_ILLEGAL_JUMP = parseInt(localStorage['HideStuffInKarma_ILLEGAL_JUMP']); } catch (e) { _HideStuffInKarma_ILLEGAL_JUMP = 0; }
		try { _HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING = parseInt(localStorage['HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING']); } catch (e) { _HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING = 0; }
		try { _HideStuffInKarma_WALL_HACK = parseInt(localStorage['HideStuffInKarma_WALL_HACK']); } catch (e) { _HideStuffInKarma_WALL_HACK = 0; }
		try { _HideStuffInKarma_TANK_ACCELERATION = parseInt(localStorage['HideStuffInKarma_TANK_ACCELERATION']); } catch (e) { _HideStuffInKarma_TANK_ACCELERATION = 0; }
		try { _HideStuffInKarma_Flood = parseInt(localStorage['HideStuffInKarma_Flood']); } catch (e) { _HideStuffInKarma_Flood = 0; }
		try { _HideStuffInKarma_VERTICAL_MOVEMENT = parseInt(localStorage['HideStuffInKarma_VERTICAL_MOVEMENT']); } catch (e) { _HideStuffInKarma_VERTICAL_MOVEMENT = 0; }
		
		try { _CommentsMenu = parseInt(localStorage['CommentsMenu']); } catch (e) { _CommentsMenu = 1; }
		try { _Comments = localStorage['Comments']; } catch (e) { _Comments = ""; }
		try { _BanReasons = localStorage['BanReasons']; } catch (e) { _BanReasons = ""; }
		
		try { _language = localStorage['language']; } catch (e) { _language = "en"; }
		
		if (_language == 'en') {
			jQuery('#LangForEN').remove();
			jQuery('body').prepend('<style id="LangForEN">.OwnBanReasonsDiv {display:none;}</style>');
		}
		else {
			jQuery('#LangForEN').remove();
		}
		
		jQuery('#FontSize').val( _FontSize );
		jQuery('#TextareaX').val( _TextareaX );
		jQuery('#TextareaY').val( _TextareaY );
		jQuery('#BackgroundColor').val( _BackgroundColor );
		jQuery('#NewMessagesStar').prop('checked', _NewMessagesStar);
		jQuery('#HideStuffInKarma_ILLEGAL_JUMP').prop('checked', _HideStuffInKarma_ILLEGAL_JUMP);
		jQuery('#HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING').prop('checked', _HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING);
		jQuery('#HideStuffInKarma_WALL_HACK').prop('checked', _HideStuffInKarma_WALL_HACK);
		jQuery('#HideStuffInKarma_TANK_ACCELERATION').prop('checked', _HideStuffInKarma_TANK_ACCELERATION);
		jQuery('#HideStuffInKarma_Flood').prop('checked', _HideStuffInKarma_Flood);
		jQuery('#HideStuffInKarma_VERTICAL_MOVEMENT').prop('checked', _HideStuffInKarma_VERTICAL_MOVEMENT);
		
		jQuery('#CommentsMenu').prop('checked', _CommentsMenu);
		jQuery('#Comments').val( _Comments );
		jQuery('#BanReasons').val( _BanReasons );
	}
	
	jQuery(this).LoadSettings();
	
	var loaded = false;
	
	// Right mouse button click on battle link will redirect current page to specific battle channel
	jQuery(document).on('contextmenu', '.msg .text a', function(e) {
		var link_txt = jQuery(this).attr('href');
		
		if ( link_txt.match(/battle\-[a-z]{2}\.html\#\/server=[A-Z0-9_]+\&battle=[a-zA-Z0-9]+/g) ) {
			
			var srv = location.search.split('&')[1].split('=')[1];
			var battle = link_txt.split('#')[1].split('&')[1].replace('battle=','');
			
			window.location.href = "/app/?chnl="+battle+"&srv="+srv;
			
			e.preventDefault();
		}
	})
	
	// make links on chat clickable
	jQuery(document).on('DOMNodeInserted', '.messages-list', function(){
		setTimeout(function() {
			jQuery('.msg:not(.ldone,.system)').each(function(){
				var message = jQuery(this).find('.text');
				
				edited_message = message.html().replace('-->','--> ').replace('<!--', ' <!--').autoLink({ target: "_blank", class: "external" }).replace('--> ','-->').replace(' <!--', '<!--');
				
				message.html(edited_message);
				
				jQuery(this).addClass('ldone');
			});
		}, 500);
	});
	
	jQuery(document).on('DOMNodeInserted', '.user-history pre', function(){
		if (_HideStuffInKarma_ILLEGAL_JUMP) {
			jQuery('div.hnp:contains("ILLEGAL_JUMP")').css('display', 'none');
			var len = jQuery('div.hnp:contains("ILLEGAL_JUMP")').length;
			if (len) {
				var div = document.createElement('div');
				div.appendChild(document.createTextNode('Hidden ILLEGAL_JUMP: ' + len));
				document.querySelector('.user-history').appendChild(div);
				//jQuery('.user-history').eq(0).append('<div>Hidden ILLEGAL_JUMP: '+len+'</div>')
			}
		}
		if (_HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING) {
			jQuery('div.hnp:contains("COMMAND_CLIENT_TIMESTAMP_HACKING")').css('display', 'none');
			var len = jQuery('div.hnp:contains("COMMAND_CLIENT_TIMESTAMP_HACKING")').length;
			if (len) {
				var div = document.createElement('div');
				div.appendChild(document.createTextNode('Hidden COMMAND_CLIENT_TIMESTAMP_HACKING: ' + len));
				document.querySelector('.user-history').appendChild(div);
				//jQuery('.user-history ').eq(0).append('<div>Hidden COMMAND_CLIENT_TIMESTAMP_HACKING: '+len+'</div>')
			}
		} 
		if (_HideStuffInKarma_WALL_HACK) {
			jQuery('div.hnp:contains("WALL_HACK")').css('display', 'none');
			var len = jQuery('div.hnp:contains("WALL_HACK")').length;
			if (len) {
				var div = document.createElement('div');
				div.appendChild(document.createTextNode('Hidden WALL_HACK: ' + len));
				document.querySelector('.user-history').appendChild(div);
				//jQuery('.user-history').eq(0).append('<div>Hidden WALL_HACK: '+len+'</div>')
			}
		} 
		if (_HideStuffInKarma_TANK_ACCELERATION) {
			jQuery('div.hnp:contains("TANK_ACCELERATION")').css('display', 'none');
			var len = jQuery('div.hnp:contains("TANK_ACCELERATION")').length;
			if (len) {
				var div = document.createElement('div');
				div.appendChild(document.createTextNode('Hidden TANK_ACCELERATION: ' + len));
				document.querySelector('.user-history').appendChild(div);
				//jQuery('.user-history').eq(0).append('<div>Hidden TANK_ACCELERATION: '+len+'</div>')
			}
		}
		if (_HideStuffInKarma_Flood) {
			jQuery('div.hnp:contains("Flood")').css('display', 'none');
			var len = jQuery('div.hnp:contains("Flood")').length;
			if (len) {
				var div = document.createElement('div');
				div.appendChild(document.createTextNode('Hidden Flood: ' + len));
				document.querySelector('.user-history').appendChild(div);
				//jQuery('.user-history').eq(0).append('<div>Hidden Flood: '+len+'</div>')
			}
		}
		if (_HideStuffInKarma_VERTICAL_MOVEMENT) {
			jQuery('div.hnp:contains("VERTICAL_MOVEMENT")').css('display', 'none');
			var len = jQuery('div.hnp:contains("VERTICAL_MOVEMENT")').length;
			if (len) {
				var div = document.createElement('div');
				div.appendChild(document.createTextNode('Hidden VERTICAL_MOVEMENT: ' + len));
				document.querySelector('.user-history').appendChild(div);
				//jQuery('.user-history').eq(0).append('<div>Hidden VERTICAL_MOVEMENT: '+len+'</div>')
			}
		}
	});
	
	jQuery(document).on('click', '.user-card a:contains("Ban"), .user-card a:contains("Bann"), .user-card a:contains("Бан")', function() {
		jQuery(this).addBanReasons();
	});
	
	jQuery(document).on('DOMNodeInserted', '#app', function(){
		
		if (!loaded && document.querySelector('.main-screen')) {
			loaded = true;
			
			if (_NewMessagesStar) {
				jQuery('body').prepend('<style id="NewMessagesStarStyle">.has-unread:after {content:" *"}</style>');
			}
			
			if (_FontSize) {
				jQuery('body').prepend('<style id="FontSizeStyle">body, body input, body textarea {font-size: ' + _FontSize + 'px;}</style>');
			}
			
			if (_BackgroundColor) {
				document.body.style.background = _BackgroundColor;
			}
			
			if (_TextareaX && _TextareaY) {
				jQuery('body').prepend('<style id="TextAreaSize">textarea:not(.settingsTextarea) {width: ' + _TextareaX + 'px; height: ' + _TextareaY + 'px;}</style>');
			}
			
			jQuery('.moderation-header').eq(0).prepend(' | <a href="" onclick="return false;" class="Settings">Settings</a>');
			jQuery('.moderation-header').eq(0).prepend('<a href="http://www.battlemod.eu/tickets" target="_blank">battlemod.eu</a>');
			jQuery('.moderation-header').eq(0).prepend('<a href="https://helpdesk.eu.tankionline.com/moderator/" target="_blank">Helpdesk</a>');
			jQuery('.moderation').append('<div class="SettingsContent" style="display:none;"></div>');
			jQuery('.SettingsContent').html(jQuery(this).SettingsContent());

			jQuery(this).addComments();
			
			setTimeout(function() {
				jQuery('.servers').prepend('<div class="battleGo"><input type="text" placeholder="Battle link or ID" class="battle_field"><input type="button" class="battle_button" value="GO"></div><br>');
			}, 1000);

			jQuery(document).off('DOMNodeInserted', '#app');
		}
		
	});
	
	jQuery(document).on('click', '.srv a', function(){
		jQuery(this).addComments();
	});
	
	jQuery(document).on('click', '.battle_button', function(){
		
		var battle_id = jQuery('.battle_field').val();
		var srv = "";
		
		try {
			srv = location.search.split('&')[1].split('=')[1];
		} catch (e) {
			
		}
		
		if (battle_id.match(/\#\/battle=[a-z0-9]+$/g)) {
			
			var battle = battle_id.split('#')[1].replace('/battle=','');
			
			window.location.href = "/app/?chnl="+battle+"&srv="+srv;
		}
		else if (battle_id.match(/^[a-z0-9]+$/)) {
			
			window.location.href = "/app/?chnl="+battle_id+"&srv="+srv;
		}
		else {
			alert('It is not link to battle or battle ID!');
		}
	});
	
	jQuery(document).keydown(function(event) {
		if (!(event.which == 192 && event.ctrlKey)) {
			return true;
		}
		
		if (jQuery('.CommentsMenu').length < 1) {
			jQuery(this).addComments();
		}
		else {
			alert('Comments already loaded...');
		}
		
		event.preventDefault();
		return false;
	});
	
	jQuery(document).on('click', '.commentAdd', function() {
		//var comment = jQuery(this).data('comment');
		var comment = this.getAttribute('data-comment');
		
		//var message = jQuery('.message-input input').val();
		var message = document.querySelector('.message-input input').value;
		
		var user = "";
		
		if (tmp = message.match(/^([a-zA-Z0-9\._-]+; )/g)) {
			user = tmp[0];
		}
		
		//jQuery('.message-input input').val(user + comment);
		//jQuery(".message-input input").eq(0).focus();
		document.querySelector('.message-input input').value = user + comment;
		document.querySelector('.message-input input').focus();
		
		var el = document.getElementById('commentInput');

		var e = document.createEvent('Event');
		e.initEvent('input', true, true);
/*		
		var e = new Event('input', {
			'bubbles': true,
			'cancelable': true
		});
*/
		el.dispatchEvent(e);
		
	});
	
	jQuery(document).on('click', '.srv a', function(){
		jQuery(this).addComments();
	});
	
	jQuery.fn.addBanReasons = function () {
		setTimeout(function() {
			var lines = _BanReasons.split('\n');
			
			for (var i = 0;i < lines.length;i++){
				var line = lines[i];
				
				if (line.length > 5) { 
					jQuery('[name="reason-type"]').parent().parent().find('select').eq(0).append(jQuery('<option>', {value: line, text: line }));
				}
			}
			
		}, 500);
	};
	
	jQuery.fn.addComments = function () {
		setTimeout(function() {
			if (_CommentsMenu) {
				if (document.querySelector('.message-input')) {
				//if (jQuery('.message-input').length) {
					
					var menuContent = jQuery(this).parseMenu();
					
					if (!document.querySelector('.CommentsMenu')) {
						var div = document.createElement('div');
						div.className = 'CommentsMenu';
						
						document.querySelector('.message-input').insertBefore(div, document.querySelector('.message-input form'));
					}
					/*
					if (jQuery('.CommentsMenu').length < 1) {
						jQuery('.message-input').prepend('<div class="CommentsMenu"></div>');
					}
					*/
					
					if (document.querySelector('.CommentsMenu nav')) {
						document.querySelector('.CommentsMenu nav').remove();
					}
					
					var nav = document.createElement('nav');
					var ul = document.createElement('ul');
					ul.className = 'nav';
					var li = document.createElement('li');
					var span = document.createElement('span');
					
					li.appendChild(span);
					li.appendChild(menuContent);
					
					ul.appendChild(li);
					nav.appendChild(ul);
					
					document.querySelector('.CommentsMenu').appendChild(nav);
					
					//jQuery('.CommentsMenu').html('<nav><ul class="nav"><li><span></span>' + menuContent + '</li></ul></nav>');
					jQuery('.message-input').css('position', 'relative');
					jQuery('.message-input input').attr('id', 'commentInput');
					jQuery('.message-input form').attr('id', 'commentForm');
				}
			}
		}, 1000);
	}
	
	jQuery.fn.parseMenu = function () {
		//var menu = "";
		var ul;
		//try {
			var lines = _Comments.split('\n');
			
			ul = document.createElement('ul');
			
			//menu = "<ul>";
			
			for (var i = 0;i < lines.length;i++){
				var line = lines[i];
				//console.log(line);
				
				if (line.length > 5) {
					
					var isSub = line.split("\\");
					
					if (isSub.length == 3) {
						//console.log(' > sub');
						
						var li = document.createElement("li");
						var span = document.createElement("span");
						span.appendChild(document.createTextNode(isSub[0]));
						li.appendChild(span);
						ul.appendChild(li);
						
						var ul2 = document.createElement('ul');
						
						ul2.appendChild(jQuery(this).parseLiMenu(isSub[2]));
						
						//menu += "<li><span>"+isSub[0]+"</span><ul>";
						//menu += jQuery(this).parseLiMenu(isSub[2]);
						
						for (var j=i+1;j<lines.length;j++) {
							tmpLine = lines[j];
							
							var isSub2 = tmpLine.split("\\");
							if (isSub2.length == 3) {
								if (isSub[0] == isSub2[0]) {
									//console.log('> sub same');
									ul2.appendChild(jQuery(this).parseLiMenu(isSub2[2]));
									//menu += jQuery(this).parseLiMenu(isSub2[2]);
								}
								else {
									i=j-1;
									break;
								}
							}
							else {
								i=j-1;
								break;
							}
							i++;
						}
						
						li.appendChild(ul2);
						
						//menu += "</ul></li>";
					}
					else {
						ul.appendChild(jQuery(this).parseLiMenu(line));
						//menu += jQuery(this).parseLiMenu(line);
					}
				}
				else {
					//console.log(' > too short');
				}
			}
			
			//menu += "<ul>";
			/*
		}
		catch (e) {
			//menu = "";
			ul = document.createElement('span');
			ul.style.display = 'none';
		}
		*/
		return ul;
		//return menu;
	}
	
	jQuery.fn.parseLiMenu = function (txt) {
		var isCorrect = txt.split('|');
		//var tmp = "";
		var li;
		
		if (isCorrect.length == 2) {
			
			li = document.createElement("li");
			var span = document.createElement("span");
			span.className = 'commentAdd';
			span.setAttribute('data-comment', isCorrect[1]);
			span.appendChild(document.createTextNode(isCorrect[0]));
			li.appendChild(span);
			
			//tmp += "<li><span class='commentAdd' data-comment='"+isCorrect[1]+"'>"+isCorrect[0]+"</span></li>";
			return li;
		}
		else {
			li = document.createElement("li");
			li.style.display = 'none';
		}
		
		return li;
	}
	
	jQuery.fn.SettingsContent = function () {
		/*
		var content = document.createElement('div');
		
		var br = document.createElement("br");
		var txt;
		
		var required = document.createElement("span");
		required.className = 'required';
		txt = document.createTextNode('*');
		required.appendChild(txt);
		
		var sTitle = document.createElement('strong');
		txt = document.createTextNode('General settings:');
		sTitle.appendChild(txt);
		
		content.appendChild(sTitle);
		content.appendChild(br);
		
		var t, tr, th, td, r=0, c=0;
		
		t = document.createElement("table");
		tr = t.insertRow(r);
		td = document.createElement('th');
		td.textAlign = 'right';
		*/
		var content = '<span class="close">&times;</span><strong>General settings:</strong><br />\
<table>\
<tr>\
<th align="right">Font size in px<span class="required">*</span>:</th>\
<td><input type="text" id="FontSize" />&nbsp;<small><strong>Default:</strong> <i>14</i></small></td>\
</tr>\
<tr>\
<th align="right">Textarea size in px<span class="required">*</span>:</th>\
<td>Width: <input type="text" size="5" id="TextareaX" /> &nbsp;Height: <input type="text" size="5" id="TextareaY" />&nbsp;<small><strong>Default:</strong> <i>300x50</i></small></td>\
</tr>\
<tr>\
<th align="right">Background:</th>\
<td><input type="text" id="BackgroundColor" size="40" />&nbsp;<small><strong>Default:</strong> <i>#112211<br />\
<strong>Example for color:</strong> #333333<br />\
<strong>Example for image:</strong> url(https://i.stack.imgur.com/IehB7.png)\
</i></small></td>\
</tr>\
<tr>\
<td colspan="2"><span class="required">*</span> - required fields</td>\
</tr>\
</table>\
\
<br />\
<strong>New messages:</strong><br />\
<label>\
<input type="checkbox" id="NewMessagesStar">\
Display white star next to the battle/channel when there are new messages\
</label>\
<br />\
<br />\
<strong>Karma cleaner:</strong><br />\
Hide entries in Karma which contain phrase:<br />\
<label><input type="checkbox" id="HideStuffInKarma_ILLEGAL_JUMP">ILLEGAL_JUMP</label><br />\
<label><input type="checkbox" id="HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING">COMMAND_CLIENT_TIMESTAMP_HACKING</label><br />\
<label><input type="checkbox" id="HideStuffInKarma_WALL_HACK">WALL_HACK</label><br />\
<label><input type="checkbox" id="HideStuffInKarma_TANK_ACCELERATION">TANK_ACCELERATION</label><br />\
<label><input type="checkbox" id="HideStuffInKarma_VERTICAL_MOVEMENT">VERTICAL_MOVEMENT</label><br />\
<label><input type="checkbox" id="HideStuffInKarma_Flood">Flood warnings and 5 min bans</label>\
<br />\
<br />\
<strong>Comments:</strong><br />\
<label>\
<input type="checkbox" id="CommentsMenu">\
Enable comments menu\
</label>\
<br />\
<br />\
<small>\
<strong>Example:</strong><br />\
<i style="padding-left:5px;">Text displayed in menu|Text inserted to comment</i><br />\
<i style="padding-left:5px;">Folder menu\\\\Text displayed in menu|Text inserted to comment</i>\
</small>\
<br />\
<textarea id="Comments" class="settingsTextarea" style="width:90%;height:150px;"></textarea><br />\
<small><span class="required">"</span> - quotation marks are not allowed and will not be saved</small>\
<br />\
<br />\
\
<div class="OwnBanReasonsDiv"><strong>Own ban reasons:</strong>\
<br />\
<small>\
<strong>Example:</strong><br />\
<i style="padding-left:5px;">First example ban reason, #rules</i><br />\
<i style="padding-left:5px;">Second example ban reason, #rules</i>\
</small>\
<br />\
<textarea id="BanReasons" class="settingsTextarea" style="width:90%;height:150px;"></textarea><br />\
<small><span class="required">"</span> - quotation marks are not allowed and will not be saved</small>\
<br />\
<br />\
</div>\
<div id="status"></div>\
<button id="save">Save</button><br />\
<small><span class="required">Warning:</span> When you save settings you need to reload page before some settings starts working</small><br />\
<br />\
<br />\
<small>&copy; Settings created by <a href="http://pl.tankiforum.com/index.php?showuser=3" target="_blank">Kamil yetj Sękalski</a> v. '+__VERSION+'</small>';
		
		return content;
	}
	
	jQuery.fn.SaveSettings = function () {
		var FontSize = jQuery('#FontSize').val();
		var TextareaX = parseInt(jQuery('#TextareaX').val());
		var TextareaY = parseInt(jQuery('#TextareaY').val());
		var BackgroundColor = jQuery('#BackgroundColor').val();
		var NewMessagesStar = jQuery('#NewMessagesStar').prop('checked') ? 1 : 0;
		var HideStuffInKarma_ILLEGAL_JUMP = _HideStuffInKarma_ILLEGAL_JUMP = jQuery('#HideStuffInKarma_ILLEGAL_JUMP').prop('checked') ? 1 : 0;
		var HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING = _HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING = jQuery('#HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING').prop('checked') ? 1 : 0;
		var HideStuffInKarma_WALL_HACK = _HideStuffInKarma_WALL_HACK = jQuery('#HideStuffInKarma_WALL_HACK').prop('checked') ? 1 : 0;
		var HideStuffInKarma_TANK_ACCELERATION = _HideStuffInKarma_TANK_ACCELERATION = jQuery('#HideStuffInKarma_TANK_ACCELERATION').prop('checked') ? 1 : 0;
		var HideStuffInKarma_Flood = _HideStuffInKarma_Flood = jQuery('#HideStuffInKarma_Flood').prop('checked') ? 1 : 0;
		var HideStuffInKarma_VERTICAL_MOVEMENT = _HideStuffInKarma_VERTICAL_MOVEMENT = jQuery('#HideStuffInKarma_VERTICAL_MOVEMENT').prop('checked') ? 1 : 0;
		
		var HideLobbyChat_DE = jQuery('#HideLobbyChat_DE').prop('checked') ? 1 : 0;
		var HideLobbyChat_EN = jQuery('#HideLobbyChat_EN').prop('checked') ? 1 : 0;
		var HideLobbyChat_PL = jQuery('#HideLobbyChat_PL').prop('checked') ? 1 : 0;
		var HideLobbyChat_RU = jQuery('#HideLobbyChat_RU').prop('checked') ? 1 : 0;
		var HideLobbyChat_PT = jQuery('#HideLobbyChat_PT').prop('checked') ? 1 : 0;
		var HideLobbyChat_ES = jQuery('#HideLobbyChat_ES').prop('checked') ? 1 : 0;
		var HideLobbyChat_other = jQuery('#HideLobbyChat_other').prop('checked') ? 1 : 0;
		var HideLobbyChat_battle = jQuery('#HideLobbyChat_battle').prop('checked') ? 1 : 0;
		
		var CommentsMenu = jQuery('#CommentsMenu').prop('checked') ? 1 : 0;
		var Comments = jQuery('#Comments').val().replace(/"/g,'');
		var BanReasons = jQuery('#BanReasons').val().replace(/"/g,'');
		
		if (!FontSize || isNaN(FontSize)) {
			alert('Missing Font size...');
			return false;
		}
		if (!TextareaX || isNaN(TextareaX)) {
			alert('Missing Textarea width...');
			return false;
		}
		if (!TextareaY || isNaN(TextareaY)) {
			alert('Missing Textarea height...');
			return false;
		}
		
		localStorage['FontSize'] = FontSize;
		localStorage['TextareaX'] = TextareaX;
		localStorage['TextareaY'] = TextareaY;
		localStorage['BackgroundColor'] = BackgroundColor;
		localStorage['NewMessagesStar'] = NewMessagesStar;
		localStorage['HideStuffInKarma_ILLEGAL_JUMP'] = HideStuffInKarma_ILLEGAL_JUMP;
		localStorage['HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING'] = HideStuffInKarma_COMMAND_CLIENT_TIMESTAMP_HACKING;
		localStorage['HideStuffInKarma_WALL_HACK'] = HideStuffInKarma_WALL_HACK;
		localStorage['HideStuffInKarma_TANK_ACCELERATION'] = HideStuffInKarma_TANK_ACCELERATION;
		localStorage['HideStuffInKarma_Flood'] = HideStuffInKarma_Flood;
		localStorage['HideStuffInKarma_VERTICAL_MOVEMENT'] = HideStuffInKarma_VERTICAL_MOVEMENT;
		//localStorage['ServerStatus'] = ServerStatus;
		//localStorage['ServerStatusPlayersInLobby'] = ServerStatusPlayersInLobby;
		
		localStorage['HideLobbyChat_DE'] = HideLobbyChat_DE;
		localStorage['HideLobbyChat_EN'] = HideLobbyChat_EN;
		localStorage['HideLobbyChat_PL'] = HideLobbyChat_PL;
		localStorage['HideLobbyChat_RU'] = HideLobbyChat_RU;
		localStorage['HideLobbyChat_PT'] = HideLobbyChat_PT;
		localStorage['HideLobbyChat_ES'] = HideLobbyChat_ES;
		localStorage['HideLobbyChat_other'] = HideLobbyChat_other;
		localStorage['HideLobbyChat_battle'] = HideLobbyChat_battle;
		
		localStorage['CommentsMenu'] = CommentsMenu;
		localStorage['Comments'] = Comments;
		localStorage['BanReasons'] = BanReasons;
		
		jQuery(this).LoadSettings();
		jQuery(this).addComments();
		
		if (NewMessagesStar) {
			if (!jQuery('#NewMessagesStarStyle').length) {
				jQuery('body').prepend('<style id="NewMessagesStarStyle">.has-unread:after {content:" *"}</style>');
			}
		}
		else {
			jQuery('#NewMessagesStarStyle').remove();
		}
		
		document.body.style.background = BackgroundColor;
		
		
		if (!jQuery('#FontSizeStyle').length) {
			jQuery('body').prepend('<style id="FontSizeStyle">body, body input, body textarea {font-size: '+FontSize+'px;}</style>');
		}
		else {
			jQuery('#FontSizeStyle').remove();
			jQuery('body').prepend('<style id="FontSizeStyle">body, body input, body textarea {font-size: '+FontSize+'px;}</style>');
		}
		
		if (!jQuery('#TextAreaSize').length) {
			jQuery('body').prepend('<style id="TextAreaSize">textarea:not(.settingsTextarea) {width: ' + TextareaX + 'px; height: ' + TextareaY + 'px;}</style>');
		}
		else {
			jQuery('#TextAreaSize').remove();
			jQuery('body').prepend('<style id="TextAreaSize">textarea:not(.settingsTextarea) {width: ' + TextareaX + 'px; height: ' + TextareaY + 'px;}</style>');
		}
		
		jQuery('#status').html('Settings saved.<br /><br />');
		setTimeout(function() {
			jQuery('#status').text('');
		}, 5000);
	}
	
	jQuery.fn.OpenSettingsMenu = function () {
		jQuery('.forbidden-words').css('display', 'none');
		jQuery('.suspicious-battles').css('display', 'none');
		jQuery('.user-card').css('display', 'none');
		jQuery('.moderation > .error').css('display', 'none');
		jQuery('.SettingsContent').css('display', 'block');
	}
	
	jQuery.fn.CloseSettingsMenu = function () {
		setTimeout(function() {
			jQuery('.forbidden-words').css('display', 'flex');
			jQuery('.suspicious-battles').css('display', 'flex');
			jQuery('.user-card').css('display', 'flex');
			jQuery('.moderation > .error').css('display', 'flex');
		}, 500);
		jQuery('.SettingsContent').css('display', 'none');
	}
	
	jQuery(document).on('click', '.moderation-header > a, .user-item > a', function(e) {
		if (jQuery(this).hasClass('Settings')) {
			if (jQuery('.SettingsContent').is(':hidden')) {
				jQuery(this).OpenSettingsMenu();
				jQuery(this).LoadSettings();
			}
			e.preventDefault();
		}
		else {
			jQuery(this).CloseSettingsMenu();
		}
	});
	
	jQuery(document).on('click', '.close', function() {
		jQuery(this).CloseSettingsMenu();
	});
	
	jQuery(document).on('submit', '.search-bar', function() {
		jQuery(this).CloseSettingsMenu();
	})
	
	jQuery(document).on('click', '#save', function() {
		jQuery(this).SaveSettings();
	});
	
});


/*

Changelog:

0.17
	- added clickable links on chat
	- click right mouse button on battle links on chat to open battle chat channel (with page reload)
	- added input box which allows you to go directly to a specific battle chat channel via battle ID or battle link
	- removed options for hiding channels
	- added possibility to hide VERTICAL_MOVEMENT entries in karma
	- added button to close settings window
0.16.1
	- some optimizations of hiding channels
0.16
	- removed server status bars and number of players on servers
	- added option to hide some lobbies from the list
	- removed own ban reasons field for users using EN version of Moderation Tool
0.15
	- fixed issue with server change of server name
0.14
	- added support for US cluster
	- removed displaying twice settings link
0.13
	- fixed problem with inserting comments on FireFox
	- added possibility to add own ban reasons
0.12
	- fixed issue with adding comments which contain apostrophe symbol
	- fixed issue with loading comments box on the server change
	- some code changes from jQuery to clear javascript
	- fixed issue when you change language on the login screen, settings were not loaded
0.11
	- fixed issue with setting background
	- red bar in servers status is now since 2300 players on it
	- added possibility to hide warns for Flood in Karma
	- added possibility to disable status bar
	- added possibility to display a number of players in the lobby on servers
	- added possibility to disable display number of players in the lobby on servers
	- some code optimizations
0.10
	- added option to hide some stuff in Karma
	- added setting to enable/disable hiding stuff in Karma
	- fixed problem with display settings and searching players
	- added automatically reloading settings after save - you don't need to reload a page to apply settings anymore
	- removed options page
	- moved some CSS declarations to the separate file
	- added an option to change the tool background 
	- added indicator shows the number of players on each server
0.9
	- moved settings into moderation tool
	- removed option to import/export settings
	- disabled possibility to edit settings on an options page
0.8
	- fixed problem with import and export settings
	- fixed problem with the height of textarea
0.7
	- fixed problem with generating menu
	- changed text-align in the menu to left
0.6
	- fixed problem with sending a message after inserting predefined message
0.5
	- removed possibility to translate some functions to EN and PL since it's already in the tool
	- removed possibility to add "(report)" text to all reasons when you work on forum reports
	- removed possibility to enter own signature in options
	- added option to enable/disable star "*" indicator when there is something new on specific chat
	- added option to change font size
	- added option to enable/disable comments
	- added option to create own comments
0.4
	- fixed problem with translating "_rules" during language changes
0.3
	- fixed translations after update of the tool
	- directed messages to you have different background
	- added option to settings to insert own nickname
0.2
	- fixed translation when you use input box to find a player
	- added default reason addition
0.1
	- the first version of script
	- possibility to translate some functions to EN and PL
	- possibility to enter own signature in options
	- possibility to set default language in options
	- added star "*" indicator when there is something new on specific chat
	- possibility to add "(report)" text to all reasons when you work on forum reports
	- changed size of text boxes for own reason of the ban and note
*/